/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118602-gd21ed2298e-20250303"
#endif /* AVUTIL_FFVERSION_H */
